### ISSUE TITLE
When run this code some problems occur

### ISSUE THREAD

**Issue by pokameng** [Siyu-C/ACAR-Net#5]
When I run this code ,it occurs : RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:32, unhandled cuda error, NCCL version 2.4.8

I take some solutions,but they seem to not work.

my script is :CUDA_VISIBLE_DEVICES='0,1' python main.py --config /home/wsm/ACAR-Net/configs/AVA/SLOWFAST_R50_baseline.yaml  --nproc_per_node 8 --backend nccl  --master_port 31114

How to solve it?
@junting

**Comment by Siyu-C** [comment]
Hi @pokameng,
This error is likely caused by the fact that you start more processes (8 as designated by --nproc_per_node) than the number of given GPUs (2 as shown in CUDA_VISIBLE_DEVICES). We generally run one process on each GPU.

**Comment by jun0wanan** [comment]
> THANKS！！！Ok&nbsp; ，I have solved this problem&nbsp; and&nbsp; it has run successfully！！！
> […](#)
> ---Original--- From: "Siyu ***@***.***&gt; Date: Fri, May 28, 2021 23:52 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [Siyu-C/ACAR-Net] When run this code some problems occur (#5) Hi @pokameng, This error is likely caused by the fact that you start more processes (8 as designated by --nproc_per_node) than the number of given GPUs (2 as shown in CUDA_VISIBLE_DEVICES). We generally run one process on each GPU. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

HI，
   Can I ask you a question about code because you have run this code ? 🙂

**Comment by pokameng** [comment]
OK



---Original---
From: ***@***.***&gt;
Date: Sun, Jun 6, 2021 15:56 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Siyu-C/ACAR-Net] When run this code some problems occur (#5)




  
THANKS！！！Ok&nbsp; ，I have solved this problem&nbsp; and&nbsp; it has run successfully！！！
 …
 ---Original--- From: "Siyu @.&gt; Date: Fri, May 28, 2021 23:52 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [Siyu-C/ACAR-Net] When run this code some problems occur (#5) Hi @pokameng, This error is likely caused by the fact that you start more processes (8 as designated by --nproc_per_node) than the number of given GPUs (2 as shown in CUDA_VISIBLE_DEVICES). We generally run one process on each GPU. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
HI，
 Can I ask you a question about code because you have run this code ? 🙂

**Comment by jun0wanan** [comment]
> OK
> […](#)

Do you know how to link 1th clip^s bbox to 2rd clip^s bbox？I have seen the code find it only use all bbox to roialign all clip？why not key frame in every clip and then link them？hope to get your reply 🙏🙏

**Comment by HaleYan** [comment]
@pokameng Hi,I also met your same problem, may I ask how to solve it, thank U
